### ISSUE TITLE
请问有没有BaseRecyclerFragment的例子？

### ISSUE THREAD

**Issue by tmxd09887** [lishide/BaseAndroidDev#1]
example里是activity/recycler/RvMultiFuncActivity.java和SwipeRVDemoActivity.java

想学习下fragment内使用BaseRecyclerViewAdapterHelper的例子

谢谢

**Comment by lishide** [comment]
example里没有继承BaseRecyclerFragment的示例展示，不过可以参考BaseRecyclerActivity，它是继承 BaseRecyclerActivity 实现列表的示例展示。用法差不多的。
